# Generated by Django 6.0.3 on 2026-03-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todo_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectedReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("review", models.TextField(blank=True)),
                ("doc_id", models.CharField(max_length=100, unique=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
